### ISSUE TITLE
Deploy Backend on Heroku

### ISSUE THREAD

**Issue by krashish8** [Spardha-IIT-BHU/Spardha21-Backend#6]
Deploy the API on Heroku. Recommendations:
- Can use python packages such as `django-heroku`, `gunicorn`.
- Set up appropriate environment variables in Heroku (`SECRET_KEY`, `DEBUG`, etc)
- Make changes to `ALLOWED_HOSTS`.

**Comment by krashish8** [comment]
@Spardha-IIT-BHU/team-2022

**Comment by Ankur-Agrawal-ece20** [comment]
Okay bhaiya
