### ISSUE TITLE
Add an endpoint to resend verification email after signup

### ISSUE THREAD

**Issue by krashish8** [Spardha-IIT-BHU/Spardha21-Backend#7]
Endpoint to resend verification email, only for those users who have not verified their email.

@Spardha-IIT-BHU/team-2022

**Comment by Ankur-Agrawal-ece20** [comment]
Should we just tell them to register again and we will send an email or in the front-end there will be a dedicated page regarding it?

**Comment by krashish8** [comment]
I think it's good to have a dedicated page in the frontend to resend the verification email (or better, just a button to resend the verification email).

Normally, upon registering, the verification mail will be sent. But, there might be cases when due to some internal errors, or due to some other issues, the mail is not delivered to the receiver's inbox. So, it's good to have an endpoint that can enable the users to get the verification email again (obviously, for only those users who haven't yet verified their email).

**Comment by Ankur-Agrawal-ece20** [comment]
Okay if the user has not verified the email we will keep an option to resend the verification email just passing his or her email.
